"""empty message

Revision ID: 3f0717c28104
Revises: 
Create Date: 2025-06-21 19:15:29.258431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0717c28104'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bible_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))

    with op.batch_alter_table('bible_stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_messages_character_id'), ['character_id'], unique=False)
        batch_op.create_foreign_key(None, 'bible_character', ['character_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_messages_character_id'))
        batch_op.drop_column('character_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('bible_stories', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('bible_character', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
