"""empty message

Revision ID: ef2bcb21da24
Revises: 
Create Date: 2025-06-25 14:27:56.080752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2bcb21da24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bible_characters', schema=None) as batch_op:
        batch_op.alter_column('book',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bible_characters', schema=None) as batch_op:
        batch_op.alter_column('book',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###
